# Controlador JDBC de MySQL
db.driver=com.mysql.cj.jdbc.Driver

# Cadena de conexión JDBC
db.url=jdbc:mysql://localhost:3307/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Credenciales de acceso
db.user=root
db.password=industryPIGS123